# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  languageName: English
  weight: 1

zh:
  languageCode: zh-Hans
  languageName: 中文
  contentDir: content/zh
  weight: 2
  title: 陈颢天
  params:
    description: 陈颢天个人主页
