main:
  - name: 首页
    url: /
    weight: 10
  - name: 经历
    url: /#experience
    weight: 11
  - name: 论文
    url: /#papers
    weight: 12
  - name: 项目
    url: /#projects
    weight: 13
  - name: 学术服务
    url: /#service
    weight: 14
  - name: 联系
    url: /#contact
    weight: 20
